import type { RichPage } from "./types";
import { measured, owned, partner, tone } from "./shared";

const img = (name: string) => `/rich/${name}.jpg`;

export const corePages: RichPage[] = [
  {
    path: "/services/ai-automation",
    title: "AI & Automation",
    description: "Voice assistants, conversational AI, and automation connected to business systems.",
    tone: tone("#16132B", "#E7E2F8", "#C4B5FD", "slate"),
    heroLayout: "cta-first",
    hero: {
      title: "AI and automation services",
      lede: "Sofnology connects AI to the systems a business already runs — voice, workflows, documents, and customer service — without treating the model as the product.",
      image: img("ai-automation-hero"),
      imageAlt: "Person with a headset beside a screen showing an abstract voice waveform",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Where AI is actually useful",
      lede: "The work is the connection: a voice agent on a real call path, a workflow that stops being manual, or an assistant limited to approved knowledge.",
      items: [
        { title: "AI voice assistants", description: "Real-time voice agents connected to business systems and the telephone path, not a demo that only works in a browser." },
        { title: "Conversational AI", description: "Customer-service and internal assistants with a defined job, a defined knowledge set, and a way to hand off." },
        { title: "Business process automation", description: "Repetitive operational steps moved into a workflow the team can see and change." },
        { title: "AI API integration", description: "Models connected to the software, CRM, database, or API that already holds the work." },
        { title: "Document and data automation", description: "Extract, classify, and route business information instead of retyping it." },
        { title: "Knowledge systems", description: "Answers limited to controlled sources, so the assistant does not invent the next step." },
      ],
    },
    stages: {
      title: "From a task to a system",
      lede: "We start with the operation that is slow or inconsistent, then decide whether a model, a workflow, or both belongs there.",
      items: [
        { title: "The task", description: "Name the work that is repeated, the system it lives in, and what a wrong answer would cost." },
        { title: "The boundary", description: "Decide what the assistant may answer, what it must look up, and when a person takes over." },
        { title: "The connection", description: "Attach it to the phone system, the API, or the documents it is allowed to use." },
        { title: "The check", description: "Review real calls or real cases before the automation is treated as finished." },
        { title: "The handover", description: "Leave a path the team can operate, including what to do when the model is unsure." },
      ],
    },
    engagements: {
      title: "Three ways to start",
      lede: "A voice path that already fails, a manual process that should not stay manual, or an assistant that cannot reach the business.",
      items: [
        { title: "Voice on a live path", pain: "The assistant breaks on a real call", description: "Repair or build the path from speech through the trunk so the voice is usable on a handset." },
        { title: "A workflow, not a chatbot", pain: "People retype the same steps", description: "Automate the handoff between tools the business already uses." },
        { title: "Knowledge with limits", pain: "Answers wander off the brief", description: "Tie the assistant to approved sources and a clear escalation." },
      ],
    },
    stack: {
      title: "What the work sits on",
      lede: "Listed where Sofnology can deliver it directly or with a specialist under Sofnology’s ownership.",
      items: [
        { category: "Voice", items: ["Speech-to-text", "Text-to-speech", "SIP"] },
        { category: "Software", items: ["Python", "Node.js", "REST APIs"] },
        { category: "Control", items: ["Approved knowledge", "Tool calling", "Human handoff"] },
      ],
    },
    workSlugs: ["ai-appointment-assistant-healthcare", "ai-voice-hr-self-service", "ai-voice-business-automation"],
    workHref: "/work/ai",
    strip: {
      eyebrow: "Engineering",
      title: "The model is only one piece",
      lede: "Speech, tool calling, and the limits around them are described on the AI and voice engineering page.",
      href: "/services/ai-voice",
      label: "See AI and voice engineering",
    },
    cta: {
      title: "Have a task that should not stay manual?",
      lede: "Tell us the system it touches and what a bad answer would cost. We will outline a practical next step.",
      ctaLabel: "Discuss an automation project",
      image: img("ai-automation-cta"),
      imageAlt: "Close view of a microphone and a dark screen with a soft abstract waveform",
    },
    faqs: [
      { question: "Do you build the phone path as well as the model?", answer: "Yes, when the assistant has to speak on a real call. Speech, the trunk, and the local phone system are treated as one path." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/voip-communication",
    title: "VoIP & Communication Systems",
    description: "PBX, contact centers, SIP, IVR, broadcasting, and AI voice connected to real telephony.",
    tone: tone("#0E2433", "#D5F4F0", "#5EEAD4", "teal"),
    heroLayout: "image-first",
    hero: {
      title: "VoIP and communication systems",
      lede: "Sofnology designs, repairs, and operates business phone systems — custom PBX, contact centers, SIP, IVR, broadcasting, and AI voice on the same infrastructure.",
      image: img("voip-communication-hero"),
      imageAlt: "Desk still life of a business handset, headset, and a dark screen",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Communication work we take on",
      lede: "The phone system, the contact center, and the voice assistant are one path. A trunk that was never finished is not a separate project from the calls that fail.",
      items: [
        { title: "Custom IP PBX", description: "Business phone platforms built around how the company actually routes calls." },
        { title: "Contact centers", description: "Inbound and outbound environments, including campaign setup and the first live period." },
        { title: "SIP trunks", description: "Carrier, DID, routing, and interoperability so calls complete in both directions." },
        { title: "IVR and routing", description: "Menus, queues, ring groups, and a fallback when the first path does not answer." },
        { title: "Voice broadcasting", description: "Outbound notifications, reminders, and campaigns with reporting." },
        { title: "WebRTC and softphones", description: "Browser and mobile calling on the same SIP infrastructure." },
        { title: "CRM and call data", description: "Click-to-call, recordings, CDR, and the customer record beside the call." },
        { title: "AI voice on the PBX", description: "An assistant attached to the phone system that already exists, not a separate demo." },
      ],
    },
    stages: {
      title: "How a voice system gets finished",
      lede: "Calls are the test. Configuration that looks right and still fails one way is not done.",
      items: [
        { title: "The failure", description: "Find where the call drops: the trunk, the dial plan, the codec, or the handset." },
        { title: "The path", description: "Treat carrier, PBX, and agent or assistant as one route." },
        { title: "The flow", description: "Menus, queues, and campaigns the operators can actually run." },
        { title: "The record", description: "CDR, recordings, and reporting the business can use." },
        { title: "The handover", description: "Training and early live support so the system does not stall after go-live." },
      ],
    },
    engagements: {
      title: "What is broken today",
      lede: "A new platform, a trunk that was never completed, or a contact center nobody was trained to run.",
      items: [
        { title: "Stand up the platform", pain: "There is no working phone system", description: "Design and install the PBX or contact center, then prove calls on real handsets." },
        { title: "Finish the trunk", pain: "Calls fail in one direction", description: "Carrier, routing, and codec work until inbound and outbound both complete." },
        { title: "Make it operable", pain: "Only one person knows the dial plan", description: "Document the flow, train operators, and stay through the first live period." },
      ],
    },
    stack: {
      title: "Platforms on the call path",
      lede: "Asterisk-based systems and the SIP stack around them. The client is named only when the work can be published.",
      items: [
        { category: "Platforms", items: ["Asterisk", "FreePBX", "VICIdial", "Issabel"] },
        { category: "Signalling", items: ["SIP", "PJSIP", "WebRTC", "RTP"] },
        { category: "Control", items: ["ARI", "AMI", "AGI", "REST API"] },
      ],
    },
    workSlugs: ["ai-voice-hr-self-service", "custom-pbx-contact-center", "voice-broadcasting-platform", "flutter-sip-softphone"],
    workHref: "/work/voip",
    strip: {
      eyebrow: "Platforms",
      title: "The systems under the calls",
      lede: "PBX, contact center, queues, recording, and AI voice as platforms, rather than a single project.",
      href: "/services/platforms/voip",
      label: "See voice platforms",
    },
    cta: {
      title: "Calls should complete. The rest is configuration.",
      lede: "Tell us whether this is a new platform, a trunk, or a system that already fails in production.",
      ctaLabel: "Talk through the phone system",
      image: img("voip-communication-cta"),
      imageAlt: "Headset and handset on a dark desk with a small status light",
    },
    faqs: [
      { question: "Do you name every telephony client?", answer: "No. Confidential work stays anonymous. A case study is published only when the engagement can be described." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/cloud-devops",
    title: "Cloud & DevOps",
    description: "Linux, cloud, deployment, monitoring, backup, and server security for production systems.",
    tone: tone("#102033", "#D7EEFB", "#7DD3FC", "sky"),
    heroLayout: "cta-first",
    hero: {
      title: "Cloud and DevOps",
      lede: "Sofnology puts applications on production infrastructure and keeps that infrastructure operable — Linux, cloud, deployment, monitoring, backup, and handover.",
      image: img("cloud-devops-hero"),
      imageAlt: "Engineer beside an open server rack in cool daylight",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Infrastructure we will actually run",
      lede: "The application is not finished when the code is. Someone has to deploy it, watch it, and restore it.",
      items: [
        { title: "Linux servers", description: "Production host configuration and ongoing administration." },
        { title: "Cloud environments", description: "Infrastructure shaped around the application, not a default account." },
        { title: "Server migration", description: "Move applications, databases, and workloads without losing the records that matter." },
        { title: "Application deployment", description: "A repeatable way to put websites, APIs, and services into production." },
        { title: "Containers and CI/CD", description: "Docker and a release path that is not someone’s laptop." },
        { title: "Monitoring and logging", description: "Enough visibility to know what failed, and where." },
        { title: "Backup and recovery", description: "A backup that has been thought through as a restore, not only a copy." },
        { title: "Hardening, DNS, and TLS", description: "Firewall, access, certificates, and the names the application is reached by." },
      ],
    },
    stages: {
      title: "From a server to an operable system",
      lede: "We treat hosting, release, and recovery as one system the team can explain after we leave.",
      items: [
        { title: "What is running", description: "Map the hosts, the data, and the path a request actually takes." },
        { title: "What must survive", description: "Decide the backup, the certificate, and the access that cannot be informal." },
        { title: "How it ships", description: "Put deployment on a path more than one person can run." },
        { title: "How you know", description: "Logs and checks that tell you it failed before a customer does." },
        { title: "Who owns it", description: "Handover so the environment is not a private notebook." },
      ],
    },
    engagements: {
      title: "The usual starting points",
      lede: "A server nobody can explain, a deploy only one person can run, or a move that has to happen without losing data.",
      items: [
        { title: "Make production explainable", pain: "Only one person knows the host", description: "Document, harden, and hand over the server that is already live." },
        { title: "Make release repeatable", pain: "Deploys happen from a laptop", description: "A container or CI path the team can run again." },
        { title: "Move it", pain: "The workload has to change homes", description: "Migration of the application and the database, with a restore plan." },
      ],
    },
    stack: {
      title: "The layer under the application",
      lede: "Linux and the usual web and data pieces. Cloud is chosen for the application, not as a logo wall.",
      items: [
        { category: "Hosts", items: ["Debian", "Ubuntu", "Docker", "Bash"] },
        { category: "Edge", items: ["Nginx", "Apache", "SSL/TLS", "DNS"] },
        { category: "Data", items: ["MySQL", "MariaDB", "PostgreSQL", "Redis"] },
      ],
    },
    workSlugs: ["linux-cloud-infrastructure"],
    workHref: "/work/cloud",
    strip: {
      eyebrow: "Engineering",
      title: "How the servers are actually run",
      lede: "Linux, Docker, web servers, and hardening, as the engineering view of this work.",
      href: "/services/devops-infrastructure",
      label: "See DevOps and infrastructure",
    },
    cta: {
      title: "Production should not depend on one person.",
      lede: "Tell us what is live today and what you are afraid would be hard to restore.",
      ctaLabel: "Review the infrastructure",
      image: img("cloud-devops-cta"),
      imageAlt: "Close photograph of server hardware and cool status lights",
    },
    faqs: [
      { question: "Do you stay after the server is up?", answer: "Yes. Managed support covers ongoing administration, certificates, and the releases that follow the first deploy." },
      measured,
      partner,
      owned,
    ],
  },
];
