import type { RichPage } from "./types";
import { measured, owned, partner, tone } from "./shared";

const img = (name: string) => `/rich/${name}.jpg`;

export const engineeringPages: RichPage[] = [
  {
    path: "/services/mobile-cross-platform",
    title: "Mobile & Cross-Platform",
    description: "How Sofnology builds Flutter, iOS, and Android applications.",
    tone: tone("#2A1218", "#FDE2E4", "#F9A8B4", "coral"),
    heroLayout: "image-first",
    hero: {
      title: "Mobile and cross-platform engineering",
      lede: "This is how mobile work is built: Flutter for a shared codebase, native release for the stores, and APIs so the app can reach the business. The service a buyer starts from is Mobile App Development.",
      image: img("mobile-cross-platform-hero"),
      imageAlt: "Two phones on a pale desk showing abstract app screens",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "How the app is put together",
      lede: "One product, two stores, and a backend the field team can actually reach.",
      items: [
        { title: "Flutter", description: "A shared Android and iOS codebase when the product does not need two native teams." },
        { title: "Android and iOS", description: "Device behaviour and store release for each platform, even when the UI is shared." },
        { title: "API integration", description: "The app calls the business system instead of keeping a private copy of the data." },
        { title: "Push and device features", description: "Notifications, camera, location, or calling only where the job needs them." },
        { title: "Store deployment", description: "Google Play and App Store submission, and the release that follows." },
        { title: "Maintenance", description: "Platform updates, fixes, and features after the first version is in people’s hands." },
      ],
    },
    stages: {
      title: "From a field job to a store release",
      lede: "The app is finished when someone can do the work on a phone and the business system knows it happened.",
      items: [
        { title: "The job", description: "What the person in the field, or the customer, has to complete away from a desk." },
        { title: "The shared app", description: "One codebase unless a platform forces a split." },
        { title: "The API", description: "Sign-in, records, and the actions that must hit the server." },
        { title: "The stores", description: "Submission, review, and a way to ship the next version." },
      ],
    },
    stack: {
      title: "The mobile stack",
      lede: "Flutter first when it fits. Native pieces where the device or the store requires them.",
      items: [
        { category: "App", items: ["Flutter", "Dart", "iOS", "Android"] },
        { category: "Connection", items: ["REST APIs", "Push", "SIP where calling is the product"] },
      ],
    },
    workSlugs: ["fix-fensterreinigung", "flutter-sip-softphone"],
    workHref: "/work/mobile",
    strip: {
      eyebrow: "Service",
      title: "Start from the mobile service",
      lede: "This page is the engineering view. Mobile App Development is the page for the engagement itself.",
      href: "/services/mobile-development",
      label: "Mobile app development",
    },
    cta: {
      title: "One product should not need two codebases by default.",
      lede: "Tell us who uses the app and which system it has to update.",
      ctaLabel: "Start a Project",
      image: img("mobile-cross-platform-cta"),
      imageAlt: "Hands holding a phone in daylight, screen abstract and unreadable",
    },
    faqs: [
      { question: "Do you ship to both stores?", answer: "Yes. Play and App Store release is part of the work, including the follow-up when a platform changes." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/ai-voice",
    title: "AI & Voice AI",
    description: "How Sofnology applies language models, speech, and voice to business systems.",
    tone: tone("#241028", "#F8E4F4", "#F0ABFC", "magenta"),
    heroLayout: "cta-first",
    hero: {
      title: "AI and voice engineering",
      lede: "The technical pieces behind AI and automation: models, speech, tool calling, and the limits we put around them. The buyer-facing service is AI & Automation.",
      image: img("ai-voice-hero"),
      imageAlt: "Studio microphone in low light with a soft magenta reflection",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "The pieces on the voice path",
      lede: "A model that cannot hear the caller, or cannot reach the business, is not a voice system.",
      items: [
        { title: "Language models", description: "Used where a defined task benefits, not as a replacement for the system of record." },
        { title: "Real-time voice", description: "An agent on a live call, not only a recording played back later." },
        { title: "Speech to text and text to speech", description: "Caller speech the system can use, and replies that stay intelligible on a phone network." },
        { title: "Tool and API calling", description: "The assistant reaches business systems instead of only chatting." },
        { title: "Knowledge limits", description: "Answers drawn from approved sources, with a stop when the source does not cover the question." },
        { title: "Guardrails", description: "Checks so the assistant does not invent the next operational step." },
      ],
    },
    stages: {
      title: "Speech has to survive the network",
      lede: "We test the path the caller actually uses: synthesis, the trunk, and the handset.",
      items: [
        { title: "The utterance", description: "What the caller says, in the languages the assistant claims to speak." },
        { title: "The media", description: "Where audio quality breaks between synthesis and the phone." },
        { title: "The action", description: "Which API or record the assistant is allowed to touch." },
        { title: "The refusal", description: "What it does when it does not know, instead of guessing." },
      ],
    },
    stack: {
      title: "Voice engineering stack",
      lede: "Speech services and the telephone path. No quality score is published without a measured record.",
      items: [
        { category: "Speech", items: ["Speech-to-text", "Text-to-speech"] },
        { category: "Telephony", items: ["SIP", "RTP", "PBX"] },
        { category: "Software", items: ["Python", "REST APIs"] },
      ],
    },
    workSlugs: ["ai-appointment-assistant-healthcare", "ai-voice-hr-self-service", "ai-voice-business-automation"],
    workHref: "/work/ai",
    strip: {
      eyebrow: "Service",
      title: "Start from the automation service",
      lede: "This page is how the voice path is engineered. AI & Automation is the engagement.",
      href: "/services/ai-automation",
      label: "AI and automation",
    },
    cta: {
      title: "If it fails on a handset, it is not done.",
      lede: "Tell us the languages, the trunk, and what the assistant is allowed to do.",
      ctaLabel: "Review a voice path",
      image: img("ai-voice-cta"),
      imageAlt: "Over-ear headset on a dark table beside a small glowing speaker",
    },
    faqs: [
      { question: "Do you publish a voice quality score?", answer: "No. We describe the path that was repaired. A number appears only when a record verifies it." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/api-integration",
    title: "API & System Integration",
    description: "REST, webhooks, CRM, ERP, payments, telephony, and sign-in connected on purpose.",
    tone: tone("#0E1A3A", "#E0E9FA", "#93C5FD", "blue"),
    heroLayout: "cta-first",
    hero: {
      title: "API and system integration",
      lede: "Integration is how separate products start behaving as one operation: records, payments, calls, and sign-in crossing the boundary on purpose.",
      image: img("api-integration-hero"),
      imageAlt: "Two laptops on a desk with a notebook of empty connected boxes",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Connections we build",
      lede: "The point is the handoff. Data that is still retyped has not been integrated.",
      items: [
        { title: "REST APIs", description: "Stable interfaces between your systems and the ones partners call." },
        { title: "Webhooks", description: "Events pushed when something changes, instead of polling by habit." },
        { title: "CRM and ERP", description: "Customer and operational records connected where the process needs them." },
        { title: "Payments", description: "Through the provider’s API, not a side channel someone reconciles later." },
        { title: "Telephony", description: "Click-to-call, call data, and voice platforms beside the customer record." },
        { title: "Sign-in and SSO", description: "One authentication story across the systems that need it." },
      ],
    },
    stages: {
      title: "A boundary with an owner",
      lede: "We name the systems, the event that should cross, and what happens when the other side is down.",
      items: [
        { title: "The systems", description: "Which products already hold the record of truth." },
        { title: "The event", description: "The change that should move, and the one that should not." },
        { title: "The contract", description: "Payloads, auth, and what a failure looks like." },
        { title: "The fallback", description: "What the operator does when the other system does not answer." },
      ],
    },
    stack: {
      title: "Integration tools",
      lede: "Ordinary web contracts. We do not add a platform unless the existing APIs cannot carry the process.",
      items: [
        { category: "Contracts", items: ["REST", "JSON", "Webhooks"] },
        { category: "Access", items: ["OAuth", "SSO"] },
        { category: "Voice", items: ["SIP", "Call events"] },
      ],
    },
    workSlugs: ["ai-voice-hr-self-service", "ai-voice-business-automation", "flutter-sip-softphone"],
    workHref: "/work",
    strip: {
      eyebrow: "Service",
      title: "When the integration is a product",
      lede: "Custom software is the page for a system that needs more than a connection between tools you already have.",
      href: "/services/software-development",
      label: "Software development",
    },
    cta: {
      title: "If someone retypes it, the systems are still separate.",
      lede: "Tell us the two systems and the moment the data should move.",
      ctaLabel: "Map an integration",
      image: img("api-integration-cta"),
      imageAlt: "Overhead of cables and a notebook with a simple unlabeled diagram",
    },
    faqs: [
      { question: "Will you replace the CRM or ERP?", answer: "Not by default. We connect the systems the business already runs, and build software only where a connection is not enough." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/databases",
    title: "Databases & Data",
    description: "MySQL, MariaDB, PostgreSQL, Redis, migrations, reporting, and backups.",
    tone: tone("#1C160C", "#F8EFD8", "#E7C56A", "gold"),
    heroLayout: "image-first",
    hero: {
      title: "Databases and data",
      lede: "Design, migration, queries, reporting, and recovery for the databases the applications already depend on.",
      image: img("databases-hero"),
      imageAlt: "Quiet desk with a monitor showing abstract rows and a closed notebook",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Data work with a restore path",
      lede: "A report that locks the application, or a backup that was never restored, is not finished data work.",
      items: [
        { title: "MySQL and MariaDB", description: "The relational stores behind many of the web and voice systems we ship." },
        { title: "PostgreSQL", description: "Where the product needs PostgreSQL specifically." },
        { title: "Redis", description: "Cache and short-lived state, not a substitute for the record." },
        { title: "Design and migration", description: "Tables shaped around the operation, and a move that can be rolled back." },
        { title: "Reporting and queries", description: "The slow path found, and views people can use without stopping the app." },
        { title: "Backup and recovery", description: "A procedure that has been tried, not only a file that exists." },
      ],
    },
    stages: {
      title: "Keep the record, then speed it up",
      lede: "We do not tune a query until we know which records must survive a migration.",
      items: [
        { title: "The record", description: "What must not be lost, and who is allowed to change it." },
        { title: "The shape", description: "Tables and indexes around the real operation." },
        { title: "The move", description: "Migration with a way back." },
        { title: "The read", description: "Reports and queries that do not take the application down." },
      ],
    },
    stack: {
      title: "Stores we operate",
      lede: "The databases already in the delivery work. We do not add a warehouse for its own sake.",
      items: [
        { category: "Relational", items: ["MySQL", "MariaDB", "PostgreSQL", "SQL"] },
        { category: "Fast state", items: ["Redis"] },
        { category: "Care", items: ["Migrations", "Backups", "Query review"] },
      ],
    },
    workSlugs: ["fix-fensterreinigung"],
    workHref: "/work/mobile",
    strip: {
      eyebrow: "Engineering",
      title: "The API in front of the data",
      lede: "Backend development is where business rules and the database meet the rest of the product.",
      href: "/services/backend-development",
      label: "Backend development",
    },
    cta: {
      title: "A backup you have not restored is a guess.",
      lede: "Tell us the database, the report that hurts, or the move you are planning.",
      ctaLabel: "Review the data",
      image: img("databases-cta"),
      imageAlt: "Close view of a server drive bay in warm light",
    },
    faqs: [
      { question: "Do you take on a database that is already in production?", answer: "Yes. Most of this work starts from a live schema: slow queries, a risky migration, or a backup that has never been tested." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/devops-infrastructure",
    title: "DevOps & Infrastructure",
    description: "Linux, Docker, CI/CD, web servers, monitoring, networking, and hardening.",
    tone: tone("#102018", "#DDF5E8", "#86EFAC", "mint"),
    heroLayout: "cta-first",
    hero: {
      title: "DevOps and infrastructure engineering",
      lede: "How servers, containers, and releases are actually run. This is the engineering view of Cloud & DevOps.",
      image: img("devops-infrastructure-hero"),
      imageAlt: "Dim room with a monitor showing an abstract terminal and a small plant",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "The release path and the host",
      lede: "Linux in production, a web server in front of the app, and a deploy that is not a personal script.",
      items: [
        { title: "Linux", description: "Production hosts, users, and the services that have to stay up." },
        { title: "Docker", description: "Containers where they make the release the same every time." },
        { title: "CI/CD", description: "A path from a change to a deployment more than one person can run." },
        { title: "Web servers", description: "Nginx or Apache in front of the application, with TLS that renews." },
        { title: "Monitoring", description: "Logs and checks so a failure is visible." },
        { title: "Networking and hardening", description: "DNS, firewall, access, patching, and certificates." },
      ],
    },
    stages: {
      title: "A host someone else can operate",
      lede: "The engineering goal is a server and a release path that survive the person who set them up.",
      items: [
        { title: "The host", description: "What is installed, what listens, and who can log in." },
        { title: "The edge", description: "Names, certificates, and the web server." },
        { title: "The release", description: "How a new version replaces the old one." },
        { title: "The watch", description: "What you look at when it fails at night." },
      ],
    },
    stack: {
      title: "Infrastructure tools",
      lede: "The same layer as Cloud & DevOps, described as engineering rather than as a service menu.",
      items: [
        { category: "Compute", items: ["Linux", "Docker", "Bash"] },
        { category: "Edge", items: ["Nginx", "Apache", "SSL/TLS"] },
        { category: "Release", items: ["CI/CD", "Cloud deployment"] },
      ],
    },
    workSlugs: ["linux-cloud-infrastructure"],
    workHref: "/work/cloud",
    strip: {
      eyebrow: "Service",
      title: "Start from Cloud & DevOps",
      lede: "This page is how the infrastructure is engineered. Cloud & DevOps is the engagement.",
      href: "/services/cloud-devops",
      label: "Cloud and DevOps",
    },
    cta: {
      title: "If the deploy lives on one laptop, it is not a pipeline.",
      lede: "Tell us how a change reaches production today.",
      ctaLabel: "Look at the release path",
      image: img("devops-infrastructure-cta"),
      imageAlt: "Keyboard and a dark monitor with soft green blocks, no readable text",
    },
    faqs: [
      { question: "Is this the same work as Cloud & DevOps?", answer: "It is the engineering view of that service: hosts, containers, web servers, and the release path. The service page is where an engagement starts." },
      measured,
      partner,
      owned,
    ],
  },
];
