import type { RichPage } from "./types";
import { measured, owned, partner, tone } from "./shared";

const img = (name: string) => `/rich/${name}.jpg`;

export const industryPages: RichPage[] = [
  {
    path: "/industries/professional-services",
    title: "Professional & Field Services",
    description: "Mobile tools, enquiry websites, and operations for service businesses.",
    tone: tone("#1C1914", "#F6EBD4", "#F5D48A", "gold"),
    heroLayout: "image-first",
    hero: {
      title: "Software for professional and field services",
      lede: "We build for service businesses: mobile tools for people on the job, websites that take an enquiry, and the operations behind both.",
      image: img("professional-services-hero"),
      imageAlt: "Field technician with a tablet beside a service van in daylight",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "What this usually includes",
      lede: "The work is the job, the enquiry, and the record of what was done. Fix-Fensterreinigung is a field-service app and website. Yanming is website and paid-search work for a repair business.",
      items: [
        { title: "Field-service apps", description: "A phone the technician can use on site, connected to the jobs and the office." },
        { title: "Enquiry websites", description: "A site that explains the service and gives a call, message, or form." },
        { title: "Scheduling and jobs", description: "Work orders that are not a spreadsheet and a group chat." },
        { title: "Search and follow-up", description: "Paid and organic search tied to the same enquiry path, when acquisition is part of the brief." },
      ],
    },
    stages: {
      title: "From the enquiry to the job",
      lede: "A service business feels the gap between the person who calls and the person who shows up.",
      items: [
        { title: "The enquiry", description: "How a customer reaches the business, and what is captured." },
        { title: "The job", description: "What the field team needs on the phone to do the work." },
        { title: "The office", description: "How the result gets back without being retyped." },
      ],
    },
    engagements: {
      title: "Where teams start",
      lede: "Paper in the field, a website that does not take the call seriously, or jobs that live in messages.",
      items: [
        { title: "A tool for the field", pain: "The job is still on paper", description: "A mobile app for the visit, the notes, and the office system." },
        { title: "A site that converts", pain: "The website does not produce enquiries", description: "Pages, calls to action, and tracking around the service you sell." },
        { title: "One operation", pain: "Office and field do not share a record", description: "The enquiry, the schedule, and the completed job in one place." },
      ],
    },
    workSlugs: ["fix-fensterreinigung", "yanming-washer-repair"],
    workHref: "/work",
    strip: {
      eyebrow: "Services",
      title: "Mobile, or the website, or both",
      lede: "Field apps start in mobile development. Enquiry sites and search start in web development and digital marketing.",
      href: "/services/mobile-development",
      label: "Mobile app development",
    },
    cta: {
      title: "The customer called. The system should already know.",
      lede: "Tell us how a job is booked today, and where that information gets lost.",
      ctaLabel: "Describe the service business",
      image: img("professional-services-cta"),
      imageAlt: "Work gloves and a phone on a wooden bench, screen turned away",
    },
    faqs: [measured, partner, owned],
  },
  {
    path: "/industries/telecom",
    title: "Telecom & Communications",
    description: "PBX, contact centers, SIP, WebRTC, broadcasting, and communication APIs.",
    tone: tone("#0B1F33", "#D5F6FB", "#67E8F9", "cyan"),
    heroLayout: "cta-first",
    hero: {
      title: "Systems for telecom and communications",
      lede: "Calls fail in one direction, or the contact center was never finished. Sofnology builds the PBX, the contact center, SIP, WebRTC, broadcasting, and the APIs around them.",
      image: img("telecom-hero"),
      imageAlt: "Dark communications desk with a handset and a soft cyan light",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "What we have actually delivered",
      lede: "Phone platforms, outbound voice, and softphones that a team can run after handover.",
      items: [
        { title: "PBX and contact centers", description: "Platforms operators can run, including the first live period." },
        { title: "SIP trunking", description: "A carrier path local phones can share." },
        { title: "Voice broadcasting", description: "Notifications, reminders, and campaigns with reporting." },
        { title: "Softphones", description: "A mobile or browser client on the same SIP infrastructure." },
      ],
    },
    stages: {
      title: "Prove it on a real call",
      lede: "Diagrams are not the test. A completed call, in both directions, is.",
      items: [
        { title: "The route", description: "Trunk, PBX, and the endpoint." },
        { title: "The behaviour", description: "Queues, broadcasts, or the assistant, whichever the business needs." },
        { title: "The evidence", description: "CDR and recordings so the path can be checked later." },
      ],
    },
    workSlugs: ["custom-pbx-contact-center", "sip-trunking-implementation", "flutter-sip-softphone"],
    workHref: "/work/voip",
    strip: {
      eyebrow: "Service",
      title: "The communication engagement",
      lede: "VoIP & Communication Systems is where this industry work is scoped.",
      href: "/services/voip-communication",
      label: "VoIP and communication systems",
    },
    cta: {
      title: "We work on the phone system, not on being a carrier.",
      lede: "Tell us the platform and the call that fails.",
      ctaLabel: "Describe the voice system",
      image: img("telecom-cta"),
      imageAlt: "Close view of a headset microphone with a cool highlight",
    },
    faqs: [
      { question: "Do you operate as a telecom carrier?", answer: "No. The work is PBX, contact center, SIP, broadcasting, and communication software for businesses that already have or need that infrastructure." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/industries/technology-saas",
    title: "Technology & SaaS",
    description: "Multi-user web platforms, APIs, and infrastructure for software companies and product teams.",
    tone: tone("#12141C", "#E6E8F5", "#C7D2FE", "slate"),
    heroLayout: "image-first",
    hero: {
      title: "Product engineering for technology and SaaS",
      lede: "We build for software companies and internal product teams: multi-user web platforms, APIs, and the infrastructure under them.",
      image: img("technology-saas-hero"),
      imageAlt: "Product designer at a laptop in a quiet studio, screen abstract",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "The product, not a slide",
      lede: "Accounts, an API other systems can call, and a place for the application to run.",
      items: [
        { title: "SaaS applications", description: "Multi-user products with roles and a reason to come back." },
        { title: "APIs", description: "A contract partners and your own clients can rely on." },
        { title: "Portals", description: "Member and customer places beside the marketing site." },
        { title: "The platform underneath", description: "Deployment, data, and access so the product can stay up." },
      ],
    },
    engagements: {
      title: "How product teams engage",
      lede: "A defined build, a team on the roadmap, or engineering added to a team you already have.",
      items: [
        { title: "A scoped product", pain: "The first version has a boundary", description: "Design, build, and handover of a platform with a clear scope." },
        { title: "A team on the roadmap", pain: "The product keeps moving", description: "Engineers aligned to an ongoing backlog, not a one-off page." },
        { title: "Extra capability", pain: "One skill is missing", description: "Staff added for API, mobile, or infrastructure without rebuilding the team." },
      ],
    },
    workSlugs: ["napc-membership-website"],
    workHref: "/work/software",
    strip: {
      eyebrow: "Platforms",
      title: "The shape of a web product",
      lede: "Web and SaaS platforms describes accounts, portals, and dashboards in more detail.",
      href: "/services/platforms/web-saas",
      label: "Web and SaaS platforms",
    },
    cta: {
      title: "A SaaS product is the account, the API, and the day after launch.",
      lede: "Tell us who the user is and what has to be true in production.",
      ctaLabel: "Outline the product",
      image: img("technology-saas-cta"),
      imageAlt: "Abstract dashboard on a monitor in a dim product studio",
    },
    faqs: [measured, partner, owned],
  },
  {
    path: "/industries/manufacturing",
    title: "Manufacturing & Operations",
    description: "Workflows, reporting, and systems for teams on the floor and in the office.",
    tone: tone("#1C140C", "#F8E7C8", "#F5C16C", "amber"),
    heroLayout: "image-first",
    hero: {
      title: "Systems for manufacturing and operations",
      lede: "We build for operational teams that need clearer workflows, reporting, and systems that connect the floor and the office. We do not claim a factory practice we have not delivered.",
      image: img("manufacturing-hero"),
      imageAlt: "Operator with a tablet on a clean factory floor",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "What operations software is for",
      lede: "The useful system is the one a supervisor and the floor can both trust.",
      items: [
        { title: "Operational dashboards", description: "A view of work in progress, not a report assembled the next morning." },
        { title: "Workflow systems", description: "Handoffs between the floor and the office with a state, not a message." },
        { title: "Reporting", description: "Numbers from the system that recorded the work." },
        { title: "Connections", description: "The tools you already run, joined where the process crosses them." },
      ],
    },
    stages: {
      title: "Start from the handoff that fails",
      lede: "We do not begin with a plant-wide claim. We begin with the step that is late, lost, or retyped.",
      items: [
        { title: "The step", description: "Where information leaves the floor or arrives at the office." },
        { title: "The record", description: "What must be stored so the next shift can see it." },
        { title: "The view", description: "The screen a supervisor will actually open." },
      ],
    },
    strip: {
      eyebrow: "Platforms",
      title: "Internal systems, not a public site",
      lede: "Business and enterprise systems covers workflows, reporting, and the tools around an operation.",
      href: "/services/platforms/business",
      label: "Business and enterprise systems",
    },
    cta: {
      title: "If the floor and the office disagree, the system is late.",
      lede: "Tell us the handoff. We will say whether it is a workflow, a report, or a connection.",
      ctaLabel: "Start a Project",
      image: img("manufacturing-cta"),
      imageAlt: "Industrial workbench with a tablet in a protective case, screen abstract",
    },
    faqs: [
      { question: "What does Sofnology build for an operation?", answer: "Workflows, reporting, and the connection between the floor and the office, for work that is already happening." },
      measured,
      partner,
      owned,
    ],
  },
];
