import type { RichPage } from "./types";
import { measured, owned, partner, tone } from "./shared";

const img = (name: string) => `/rich/${name}.jpg`;

export const platformPages: RichPage[] = [
  {
    path: "/services/platforms/cloud-linux",
    title: "Cloud & Linux Infrastructure",
    description: "The server, database, deployment, monitoring, backup, and security layer under an application.",
    tone: tone("#0C1612", "#D8F3E8", "#6EE7B7", "emerald"),
    heroLayout: "image-first",
    hero: {
      title: "Cloud and Linux platforms",
      lede: "The layer under an application: Linux servers, cloud environments, web servers, databases, deployment, monitoring, backup, and access.",
      image: img("cloud-linux-hero"),
      imageAlt: "Row of rack servers in a clean, cool server room",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Platforms we design or operate",
      lede: "An application with nowhere reliable to run is not a finished system.",
      items: [
        { title: "Linux servers", description: "Production hosts and the administration around them." },
        { title: "Cloud environments", description: "Infrastructure shaped around the application." },
        { title: "Web and application servers", description: "Nginx, Apache, and the process behind them." },
        { title: "Databases", description: "MySQL, MariaDB, PostgreSQL, and Redis on the same platform story." },
        { title: "Deployment", description: "How a release reaches the server." },
        { title: "Monitoring, backup, and security", description: "Visibility, a restore procedure, TLS, firewall, and patching." },
      ],
    },
    stack: {
      title: "What this platform includes",
      lede: "The pieces we will name in a handover, not a catalogue of every cloud logo.",
      items: [
        { category: "Compute", items: ["Debian", "Ubuntu", "Docker"] },
        { category: "Edge and data", items: ["Nginx", "MySQL", "PostgreSQL"] },
      ],
    },
    workSlugs: ["linux-cloud-infrastructure"],
    workHref: "/work/cloud",
    strip: {
      eyebrow: "Service",
      title: "Run it as an engagement",
      lede: "Cloud & DevOps is the service for standing this platform up and keeping it operable.",
      href: "/services/cloud-devops",
      label: "Cloud and DevOps",
    },
    cta: {
      title: "The platform is whatever still runs after we leave.",
      lede: "Tell us the application and where it has to live.",
      ctaLabel: "Plan the platform",
      image: img("cloud-linux-cta"),
      imageAlt: "Close photograph of network ports and a labeled-free patch panel",
    },
    faqs: [measured, partner, owned],
  },
  {
    path: "/services/platforms/voip",
    title: "VoIP & Contact Center Platforms",
    description: "PBX, contact centers, SIP, IVR, queues, WebRTC, broadcasting, recording, and AI voice.",
    tone: tone("#1A140C", "#FDE8D0", "#FDBA74", "orange"),
    heroLayout: "cta-first",
    hero: {
      title: "VoIP and contact center platforms",
      lede: "The communication platforms Sofnology designs, integrates, or operates — from the PBX and the contact center to recording and an assistant on the same path.",
      image: img("voip-platform-hero"),
      imageAlt: "Contact-center headset on a desk with a soft amber lamp",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "The platform, not only one feature",
      lede: "A phone system and a contact center that do not meet are two unfinished platforms.",
      items: [
        { title: "PBX", description: "Business phone platforms, including Asterisk-based systems." },
        { title: "Contact centers", description: "Inbound and outbound agent environments." },
        { title: "SIP, IVR, and queues", description: "Trunks, menus, waiting, and where the call lands." },
        { title: "WebRTC and broadcasting", description: "Browser calling, and outbound notifications with a record." },
        { title: "Recording and reporting", description: "CDR, recordings, and an operational view." },
        { title: "AI voice", description: "An assistant attached to the platform that already carries the calls." },
      ],
    },
    stack: {
      title: "Voice platforms",
      lede: "Named where we have delivered them. Confidential clients stay unnamed.",
      items: [
        { category: "Systems", items: ["Asterisk", "FreePBX", "VICIdial"] },
        { category: "Path", items: ["SIP", "WebRTC", "Queues"] },
      ],
    },
    workSlugs: ["ai-voice-hr-self-service", "custom-pbx-contact-center", "voice-broadcasting-platform", "ai-voice-business-automation"],
    workHref: "/work/voip",
    strip: {
      eyebrow: "Service",
      title: "Fix or build the call path",
      lede: "VoIP & Communication Systems is the engagement for a platform that has to carry real calls.",
      href: "/services/voip-communication",
      label: "VoIP and communication systems",
    },
    cta: {
      title: "Add the assistant only after the trunk works.",
      lede: "Tell us which platform is already in place, and which calls fail.",
      ctaLabel: "Review the voice platform",
      image: img("voip-platform-cta"),
      imageAlt: "Row of desk phones in soft focus, no readable screens",
    },
    faqs: [
      { question: "Do you publish carrier account details?", answer: "No. Trunks, logins, and customer numbers stay off the site. The case study describes the system, not the credentials." },
      measured,
      partner,
      owned,
    ],
  },
  {
    path: "/services/platforms/web-saas",
    title: "Web & SaaS Platforms",
    description: "SaaS applications, portals, dashboards, and multi-user web systems.",
    tone: tone("#10182E", "#E4E9F8", "#A5B4FC", "blue"),
    heroLayout: "image-first",
    hero: {
      title: "Web and SaaS platforms",
      lede: "Multi-user products: SaaS applications, customer and member portals, dashboards, and the internal tools beside the public site.",
      image: img("web-saas-hero"),
      imageAlt: "Laptop on a white desk showing an abstract product dashboard",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Platforms people sign in to",
      lede: "A public site with no place for members, customers, or staff is not this kind of system.",
      items: [
        { title: "SaaS applications", description: "Accounts, roles, and a product people return to." },
        { title: "Customer and member portals", description: "A private web place, including association and membership platforms." },
        { title: "Dashboards", description: "Operational and management views of the same data." },
        { title: "Internal applications", description: "Tools for the team, separate from the marketing site." },
        { title: "Subscriptions", description: "Access that continues because the account continues." },
      ],
    },
    stack: {
      title: "How these platforms are built",
      lede: "The web stack already used on delivered membership and product work.",
      items: [
        { category: "Interface", items: ["TypeScript", "React"] },
        { category: "Application", items: ["PHP", "MySQL", "PostgreSQL"] },
      ],
    },
    workSlugs: ["napc-membership-website"],
    workHref: "/work/web",
    strip: {
      eyebrow: "Service",
      title: "When you need the website first",
      lede: "Web development covers the product and the public site. This page is the platform shape: accounts, roles, and ongoing use.",
      href: "/services/web-development",
      label: "Web development",
    },
    cta: {
      title: "A portal is not a brochure with a login painted on.",
      lede: "Tell us who signs in, and what they have to be able to do.",
      ctaLabel: "Shape the platform",
      image: img("web-saas-cta"),
      imageAlt: "Person from behind at a laptop in a bright room, screen abstract",
    },
    faqs: [measured, partner, owned],
  },
  {
    path: "/services/platforms/business",
    title: "Business & Enterprise Systems",
    description: "Internal software, workflows, CRM and ERP connections, reporting, and automation.",
    tone: tone("#1C140E", "#F6E6D4", "#E7C8A0", "gold"),
    heroLayout: "cta-first",
    hero: {
      title: "Business and enterprise systems",
      lede: "Internal software, workflows, CRM and ERP connections, reporting, and the automation between them.",
      image: img("business-systems-hero"),
      imageAlt: "Operations desk with a clipboard, laptop, and morning light",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "Systems the company runs on",
      lede: "Work that still moves by email has not been given a system.",
      items: [
        { title: "Internal software", description: "Tools shaped to how the company works, not a generic suite renamed." },
        { title: "Workflows", description: "Handoffs that have an owner and a state." },
        { title: "CRM and ERP connections", description: "Customer and operational records joined where the process needs both." },
        { title: "Reporting and dashboards", description: "Numbers from the systems of record, and a view of work in progress." },
        { title: "Automation", description: "Repeatable steps between tools, with a person where judgment is required." },
      ],
    },
    stack: {
      title: "How the systems connect",
      lede: "APIs and the databases behind internal tools. We connect what you have before replacing it.",
      items: [
        { category: "Integration", items: ["REST APIs", "Webhooks"] },
        { category: "Data", items: ["MySQL", "PostgreSQL"] },
      ],
    },
    workSlugs: ["ai-voice-hr-self-service", "napc-membership-website", "ai-voice-business-automation"],
    workHref: "/work",
    strip: {
      eyebrow: "Engineering",
      title: "The connections between the tools",
      lede: "API and system integration is the page for the boundary itself.",
      href: "/services/api-integration",
      label: "API and system integration",
    },
    cta: {
      title: "If the process lives in an inbox, it is not a system yet.",
      lede: "Tell us the handoff that keeps getting lost.",
      ctaLabel: "Describe the operation",
      image: img("business-systems-cta"),
      imageAlt: "Paper workflow cards beside a laptop, no readable writing",
    },
    faqs: [measured, partner, owned],
  },
  {
    path: "/services/platforms/marketing",
    title: "Marketing & Analytics Platforms",
    description: "Google Ads, Analytics, Tag Manager, Search Console, tracking, CMS, and landing pages.",
    tone: tone("#24141C", "#F8E4EE", "#F9A8D4", "hotpink"),
    heroLayout: "cta-first",
    hero: {
      title: "Marketing and analytics platforms",
      lede: "The systems behind acquisition: ads, analytics, tags, search, the CMS, and the landing pages they point at.",
      image: img("marketing-platform-hero"),
      imageAlt: "Evening laptop with an abstract analytics layout and a phone beside it",
      ctaLabel: "Start a Project",
    },
    services: {
      title: "One measurement setup",
      lede: "Campaigns with no conversion record, and a website the ads do not match, are the same problem.",
      items: [
        { title: "Google Ads", description: "Account structure and ongoing paid search." },
        { title: "Analytics and Search Console", description: "Traffic and how the site is seen in search, read against enquiries." },
        { title: "Tag Manager", description: "Tags and conversion events in one place." },
        { title: "Conversion tracking", description: "Calls, forms, and other actions worth counting. Not guessed customers." },
        { title: "CMS and landing pages", description: "The site and the pages a campaign is allowed to send people to." },
        { title: "Reporting", description: "Spend and enquiries in one view, without invented totals." },
      ],
    },
    stack: {
      title: "The marketing systems",
      lede: "Configured and connected. Performance figures stay out until the account or the business record verifies them.",
      items: [
        { category: "Acquisition", items: ["Google Ads", "Search Console"] },
        { category: "Measurement", items: ["Google Analytics", "Tag Manager", "Conversion events"] },
      ],
    },
    workSlugs: ["yanming-washer-repair"],
    workHref: "/work/growth",
    strip: {
      eyebrow: "Service",
      title: "Run it as digital marketing",
      lede: "This page is the platform set. Digital marketing is the ongoing engagement.",
      href: "/services/digital-marketing",
      label: "Digital marketing",
    },
    cta: {
      title: "Tags are not a strategy. They are how you see the strategy.",
      lede: "Tell us which accounts exist and which action should count as an enquiry.",
      ctaLabel: "Connect the accounts",
      image: img("marketing-platform-cta"),
      imageAlt: "Notebook, sticky notes, and a blurred phone screen on a dark desk",
    },
    faqs: [
      { question: "Are Google Ads conversions the same as customers?", answer: "No. A conversion is the event that was tagged. It is a confirmed customer only when the business has validated it." },
      measured,
      partner,
      owned,
    ],
  },
];
