export type ServiceGroup = "core" | "engineering" | "platform";

export type ServicePageData = {
  slug: string;
  path: string;
  title: string;
  description: string;
  lede: string;
  image: string;
  imageAlt: string;
  group: ServiceGroup;
  cards: Array<{ title: string; description: string }>;
  problems: string[];
  technologies: string[];
  workSlugs: string[];
  faqs: Array<{ question: string; answer: string }>;
};

const partner =
  "Where a project needs a specialist, Sofnology keeps ownership, technical oversight, and communication, and can add a vetted engineer or delivery partner for that part of the work.";

function faqs(topic: string): ServicePageData["faqs"] {
  return [
    {
      question: `Do you deliver ${topic} in-house?`,
      answer: `Core direction stays with Sofnology. ${partner}`,
    },
    {
      question: "How does a project start?",
      answer:
        "With a short discovery conversation. We clarify the outcome, the current system, and whether the next step is a scoped build, a team, or support.",
    },
    {
      question: "Will you publish metrics we have not measured?",
      answer:
        "No. Case studies describe what was delivered. Numbers appear only when a real record verifies them.",
    },
    {
      question: "Who owns the result?",
      answer:
        "The client owns the agreed deliverables, source, and configured systems once the handover terms in the agreement are complete.",
    },
  ];
}

export const servicePages: ServicePageData[] = [
  {
    slug: "software-development",
    path: "/services/software-development",
    title: "Custom Software Development",
    description:
      "Software designed around real business workflows, from internal systems and APIs to customer-facing platforms.",
    lede: "We design and build software around real business workflows — from internal systems and APIs to customer-facing platforms and SaaS products.",
    image: "/enterprise-services.jpg",
    imageAlt: "Engineering collaboration in a modern workspace",
    group: "core",
    cards: [
      { title: "Custom Software Development", description: "Business-specific software designed around operational requirements." },
      { title: "SaaS Product Development", description: "Multi-user and subscription-based software platforms." },
      { title: "Backend & API Development", description: "Backend systems, APIs, authentication, business logic, and integrations." },
      { title: "Enterprise Applications", description: "Internal platforms, operational systems, dashboards, and business applications." },
      { title: "System Integration", description: "Connect existing software, APIs, databases, CRM, ERP, and external platforms." },
      { title: "Legacy System Modernization", description: "Improve or rebuild older applications and infrastructure." },
      { title: "MVP & Product Development", description: "Turn an idea into a functional first product that can be tested and expanded." },
      { title: "Software Testing & QA", description: "Functional testing, API testing, regression testing, and QA automation." },
    ],
    problems: ["Manual business processes", "Disconnected software", "Legacy systems", "Scaling limitations", "Missing integrations"],
    technologies: ["PHP", "Python", "Node.js", "JavaScript / TypeScript", "REST APIs", "MySQL", "PostgreSQL", "Redis", "Docker", "Linux", "Cloud platforms"],
    workSlugs: ["napc-membership-website", "linux-cloud-infrastructure"],
    faqs: faqs("custom software"),
  },
  {
    slug: "web-development",
    path: "/services/web-development",
    title: "Web Development",
    description: "Business websites, web applications, portals, and dashboards built around enquiries and operations.",
    lede: "We build websites and browser-based systems that help a business look credible, take enquiries, and run day-to-day work.",
    image: "/digital-growth.jpg",
    imageAlt: "Digital product workspace",
    group: "core",
    cards: [
      { title: "Business Website Development", description: "Professional websites designed around credibility, enquiries, and business growth." },
      { title: "Custom Web Applications", description: "Browser-based business software and customer-facing applications." },
      { title: "Customer & Member Portals", description: "Secure portals for customers, employees, members, or partners." },
      { title: "Dashboard Development", description: "Operational, reporting, analytics, and management dashboards." },
      { title: "E-commerce Development", description: "Online stores and digital commerce systems." },
      { title: "CMS Development", description: "Flexible websites that allow teams to manage their own content." },
      { title: "Landing Pages", description: "Conversion-focused pages for marketing campaigns and lead generation." },
      { title: "Website Maintenance & Optimization", description: "Performance improvements, updates, security maintenance, bug fixes, and ongoing support." },
    ],
    problems: ["Outdated websites", "Enquiries that never reach the team", "Content nobody can update", "Portals bolted on later"],
    technologies: ["JavaScript / TypeScript", "React", "Next.js", "PHP", "CMS platforms", "MySQL", "PostgreSQL"],
    workSlugs: ["napc-membership-website", "yanming-digital-growth"],
    faqs: faqs("web development"),
  },
  {
    slug: "mobile-development",
    path: "/services/mobile-development",
    title: "Mobile App Development",
    description: "Flutter, iOS, and Android applications connected to real business systems.",
    lede: "We design and ship mobile applications for field teams and customers, including cross-platform Flutter apps and store release.",
    image: "/conversation.jpg",
    imageAlt: "Collaborative workspace conversation",
    group: "core",
    cards: [
      { title: "Cross-Platform App Development", description: "Flutter-based Android and iOS applications from a shared codebase." },
      { title: "iOS Application Development", description: "Applications designed and delivered for Apple's ecosystem." },
      { title: "Android Application Development", description: "Applications for Android phones and tablets." },
      { title: "Business Mobile Applications", description: "Mobile tools connected to existing business operations and systems." },
      { title: "API-Integrated Mobile Apps", description: "Apps connected with business APIs, databases, CRM, ERP, or third-party platforms." },
      { title: "Communication & VoIP Apps", description: "SIP, calling, WebRTC, and real-time communication applications." },
      { title: "App Store Deployment", description: "Google Play and Apple App Store publishing and release support." },
      { title: "Mobile App Maintenance", description: "Bug fixes, platform updates, feature development, and ongoing support." },
    ],
    problems: ["Two native codebases", "Field teams still on paper", "Apps that cannot reach the business system", "Store releases that stall"],
    technologies: ["Flutter", "iOS", "Android", "PHP", "MySQL", "REST APIs", "SIP"],
    workSlugs: ["fix-fensterreinigung-mobile-app", "flutter-sip-softphone"],
    faqs: faqs("mobile apps"),
  },
  {
    slug: "ai-automation",
    path: "/services/ai-automation",
    title: "AI & Automation",
    description: "Voice assistants, conversational AI, and automation connected to business systems.",
    lede: "We connect AI and automation to the systems a business already runs — voice, workflows, documents, and customer service — without treating the model as the product.",
    image: "/digital-growth.jpg",
    imageAlt: "Digital systems workspace",
    group: "core",
    cards: [
      { title: "AI Voice Assistants", description: "Real-time AI voice agents connected with business systems and telephony." },
      { title: "Conversational AI", description: "Customer-service assistants, internal assistants, and intelligent chat experiences." },
      { title: "Business Process Automation", description: "Automate repetitive operational workflows and business processes." },
      { title: "AI API Integration", description: "Connect AI models with existing software, APIs, CRM, databases, and operational systems." },
      { title: "Workflow Automation", description: "Connect applications and automate actions between business tools." },
      { title: "Document & Data Automation", description: "Extract, transform, classify, and process business information." },
      { title: "AI Knowledge Systems", description: "AI assistants connected with controlled business knowledge and information sources." },
      { title: "AI-enabled Customer Service", description: "Voice and digital automation designed around customer-support workflows." },
    ],
    problems: ["Repetitive manual work", "Assistants that cannot reach the phone system", "Knowledge trapped in documents", "Customer service that does not scale"],
    technologies: ["Voice AI", "Speech-to-text", "Text-to-speech", "REST APIs", "SIP", "Python", "Node.js"],
    workSlugs: ["ai-voice-business-automation"],
    faqs: faqs("AI and automation"),
  },
  {
    slug: "voip-communication",
    path: "/services/voip-communication",
    title: "VoIP & Communication Systems",
    description: "PBX, contact centers, SIP, IVR, broadcasting, and AI voice connected to real telephony.",
    lede: "We design, repair, and operate business communication systems — from custom PBX and contact centers to SIP, IVR, and AI voice on the same infrastructure.",
    image: "/Portfolio/4.jpg",
    imageAlt: "Studio still of a voice platform stack",
    group: "core",
    cards: [
      { title: "Custom IP PBX", description: "Business communication platforms built around custom requirements." },
      { title: "Contact Center Solutions", description: "Inbound and outbound contact-center environments." },
      { title: "SIP Trunk Integration", description: "Carrier, DID, SIP trunk, routing, and interoperability configuration." },
      { title: "IVR & Call Routing", description: "Interactive voice response, queues, ring groups, routing logic, and fallback flows." },
      { title: "Voice Broadcasting", description: "Automated outbound calling, notifications, reminders, and campaign systems." },
      { title: "WebRTC & Softphone Solutions", description: "Browser and mobile communication applications." },
      { title: "CRM & Telephony Integration", description: "Click-to-call, call data, CRM APIs, call automation, and customer workflows." },
      { title: "Call Recording & Reporting", description: "CDR, recordings, analytics, operational reporting, and custom dashboards." },
      { title: "AI Voice Integration", description: "Connect AI voice assistants with existing PBX and communication infrastructure." },
    ],
    problems: ["Calls that fail in one direction", "Trunks that were never finished", "Contact centers nobody was trained to run", "AI voice that sounds broken on a real handset"],
    technologies: ["Asterisk", "FreePBX", "VICIdial", "Issabel", "SIP", "PJSIP", "WebRTC", "ARI", "AMI", "AGI", "RTP", "Linux", "REST API"],
    workSlugs: ["custom-pbx-contact-center", "voice-broadcasting-platform", "flutter-sip-softphone"],
    faqs: faqs("VoIP and communication systems"),
  },
  {
    slug: "digital-marketing",
    path: "/services/digital-marketing",
    title: "Digital Marketing",
    description: "Google Ads, SEO, tracking, and landing pages planned with the website they send people to.",
    lede: "We plan and run acquisition work that stays tied to the website: paid search, SEO, tracking, and the pages people actually land on.",
    image: "/digital-growth.jpg",
    imageAlt: "Digital growth workspace",
    group: "core",
    cards: [
      { title: "Google Ads Management", description: "Ongoing management and optimization of paid-search campaigns." },
      { title: "Google Ads Account Setup", description: "Campaign architecture, keyword planning, ad groups, targeting, and account configuration." },
      { title: "SEO & Local SEO", description: "Improve organic search visibility and local search presence." },
      { title: "Google Tag Manager & Conversion Tracking", description: "Configure measurable website actions, conversions, calls, forms, and marketing events." },
      { title: "Analytics & Reporting", description: "Google Analytics, campaign reporting, traffic analysis, and business-focused performance reporting." },
      { title: "Website & Landing Page Optimization", description: "Improve pages used by paid and organic traffic." },
      { title: "Conversion Rate Optimization", description: "Identify and improve friction in enquiry and conversion journeys." },
      { title: "Website Maintenance", description: "Ongoing website content, technical, performance, and campaign-related maintenance." },
      { title: "Search & Content Strategy", description: "Keyword strategy, landing-page planning, search-focused content, and acquisition planning." },
    ],
    problems: ["Ads with no landing page", "Forms that are not tracked", "SEO detached from the service the business sells", "Reports nobody can act on"],
    technologies: ["Google Ads", "Google Analytics", "Google Tag Manager", "Google Search Console", "SEO tools", "CMS platforms"],
    workSlugs: ["yanming-digital-growth"],
    faqs: faqs("digital marketing"),
  },
  {
    slug: "cloud-devops",
    path: "/services/cloud-devops",
    title: "Cloud & DevOps",
    description: "Linux, cloud, deployment, monitoring, backup, and server security for production systems.",
    lede: "We put applications on production infrastructure and keep that infrastructure operable — Linux, cloud, deployment, monitoring, and handover.",
    image: "/enterprise-services.jpg",
    imageAlt: "Infrastructure and engineering workspace",
    group: "core",
    cards: [
      { title: "Linux Server Administration", description: "Production Linux server configuration and ongoing administration." },
      { title: "Cloud Infrastructure", description: "Cloud environments designed around application requirements." },
      { title: "Server Migration", description: "Move applications, databases, and workloads between environments." },
      { title: "Application Deployment", description: "Production deployment of websites, APIs, software, and infrastructure." },
      { title: "Containers & CI/CD", description: "Docker, automated deployments, and repeatable release workflows." },
      { title: "Monitoring & Logging", description: "Application and infrastructure visibility, diagnostics, and operational monitoring." },
      { title: "Backup & Recovery", description: "Server, database, and application backup strategies." },
      { title: "Security Hardening", description: "Firewall, access control, SSL/TLS, patching, and server-level security improvements." },
      { title: "DNS, SSL & Networking", description: "Domain, certificate, routing, connectivity, and application networking support." },
      { title: "Managed Infrastructure Support", description: "Ongoing server and production-environment maintenance." },
    ],
    problems: ["Servers nobody can explain", "Deploys that only one person can run", "No backup worth restoring", "Certificates and DNS left to chance"],
    technologies: ["Debian", "Ubuntu", "Docker", "Nginx", "Apache", "MySQL", "MariaDB", "PostgreSQL", "Redis", "Cloud platforms", "Bash", "SSL/TLS"],
    workSlugs: ["linux-cloud-infrastructure"],
    faqs: faqs("cloud and DevOps"),
  },
  {
    slug: "backend-development",
    path: "/services/backend-development",
    title: "Backend Development",
    description: "APIs, business logic, authentication, and database-backed applications.",
    lede: "Backend work is how the services above stay reliable: APIs, business rules, sign-in, and the data underneath.",
    image: "/enterprise-services.jpg",
    imageAlt: "Engineering workspace",
    group: "engineering",
    cards: [
      { title: "API Development", description: "REST APIs other products and partners can call." },
      { title: "Business Logic", description: "Rules that belong on the server, not copied into every screen." },
      { title: "Authentication & Authorization", description: "Sign-in and permissions matched to real roles." },
      { title: "Third-Party Integration", description: "External systems connected at the API boundary." },
      { title: "Database-backed Applications", description: "Applications whose state lives in a database you can operate." },
      { title: "Microservices & Services", description: "Service boundaries only where they reduce operational pain." },
      { title: "Performance & Scalability", description: "Bottlenecks found on the path users actually hit." },
    ],
    problems: ["Business rules trapped in the interface", "APIs that cannot be trusted", "Permissions added after launch"],
    technologies: ["Node.js", "PHP", "Python", "REST APIs", "MySQL", "PostgreSQL", "Redis"],
    workSlugs: ["fix-fensterreinigung-mobile-app", "napc-membership-website"],
    faqs: faqs("backend development"),
  },
  {
    slug: "frontend-development",
    path: "/services/frontend-development",
    title: "Frontend Development",
    description: "Responsive interfaces, web applications, dashboards, and admin panels.",
    lede: "Interfaces for the products Sofnology ships: marketing sites, web apps, dashboards, and the admin panels operators use.",
    image: "/digital-growth.jpg",
    imageAlt: "Product interface workspace",
    group: "engineering",
    cards: [
      { title: "Responsive Web Interfaces", description: "Layouts that hold up on a phone and on a desk." },
      { title: "Web Applications", description: "Browser software, not only a brochure site." },
      { title: "Dashboards", description: "Operational and reporting views." },
      { title: "Admin Panels", description: "The screens a team uses to run the product." },
      { title: "Frontend API Integration", description: "Interfaces bound to real APIs." },
      { title: "Design System Implementation", description: "Repeated components instead of one-off screens." },
      { title: "Performance Optimization", description: "Pages that stay usable on ordinary connections." },
    ],
    problems: ["Interfaces that only work on a laptop", "Admin tools nobody can use", "Frontends detached from the API"],
    technologies: ["TypeScript", "React", "Next.js", "CSS"],
    workSlugs: ["napc-membership-website", "yanming-digital-growth"],
    faqs: faqs("frontend development"),
  },
  {
    slug: "mobile-cross-platform",
    path: "/services/mobile-cross-platform",
    title: "Mobile & Cross-Platform",
    description: "How Sofnology builds Flutter, iOS, and Android applications.",
    lede: "This page explains how mobile work is built. The service a buyer starts from is Mobile App Development.",
    image: "/conversation.jpg",
    imageAlt: "Product conversation",
    group: "engineering",
    cards: [
      { title: "Flutter", description: "Shared Android and iOS codebase." },
      { title: "Android", description: "Android phones and tablets." },
      { title: "iOS", description: "Apple devices and App Store release." },
      { title: "API Integration", description: "Apps connected to business APIs." },
      { title: "Push Notifications", description: "Messages that belong to the product, not a bolt-on." },
      { title: "Device Features", description: "Camera, location, and calling where the job needs them." },
      { title: "Application Deployment", description: "Store submission and release support." },
    ],
    problems: ["Separate iOS and Android teams for one product", "Apps that cannot call the API", "Releases stuck outside the stores"],
    technologies: ["Flutter", "Dart", "iOS", "Android", "REST APIs"],
    workSlugs: ["fix-fensterreinigung-mobile-app", "flutter-sip-softphone"],
    faqs: faqs("cross-platform mobile"),
  },
  {
    slug: "ai-voice",
    path: "/services/ai-voice",
    title: "AI & Voice AI",
    description: "How Sofnology applies language models, speech, and voice to business systems.",
    lede: "This page explains the technical pieces behind AI & Automation: models, speech, tool calling, and the limits we put around them.",
    image: "/Portfolio/1.jpg",
    imageAlt: "Studio still of a voice assistant path",
    group: "engineering",
    cards: [
      { title: "Large Language Models", description: "Models used where they help a defined task." },
      { title: "Real-time Voice AI", description: "Voice agents on a live call path." },
      { title: "Speech-to-Text", description: "Turning caller speech into text the system can use." },
      { title: "Text-to-Speech", description: "Spoken replies that survive a real phone network." },
      { title: "Tool / API Calling", description: "The assistant can reach business systems, not only chat." },
      { title: "Business Knowledge Integration", description: "Answers limited to approved sources." },
      { title: "AI Workflow Design", description: "Where the model sits in the operation." },
      { title: "Guardrails & Evaluation", description: "Checks so the assistant does not invent the next step." },
    ],
    problems: ["A model with no access to the business", "Voice that fails on a handset", "Assistants that answer outside their brief"],
    technologies: ["Speech-to-text", "Text-to-speech", "SIP", "REST APIs", "Python"],
    workSlugs: ["ai-voice-business-automation"],
    faqs: faqs("voice AI"),
  },
  {
    slug: "api-integration",
    path: "/services/api-integration",
    title: "API & System Integration",
    description: "REST, webhooks, CRM, ERP, payments, telephony, and sign-in connected on purpose.",
    lede: "Integration is how separate products start behaving as one operation.",
    image: "/enterprise-services.jpg",
    imageAlt: "Systems integration workspace",
    group: "engineering",
    cards: [
      { title: "REST APIs", description: "Stable interfaces between your systems." },
      { title: "Webhooks", description: "Events pushed when something changes." },
      { title: "CRM Integration", description: "Customer records connected to the work." },
      { title: "ERP Integration", description: "Operational systems connected where the process needs them." },
      { title: "Payment/API Integration", description: "Payments through the provider’s API, not a side channel." },
      { title: "Telephony Integration", description: "Click-to-call, call data, and voice platforms." },
      { title: "Third-Party Systems", description: "The tools the business already pays for." },
      { title: "Authentication & SSO", description: "One sign-in story across the systems that need it." },
    ],
    problems: ["Data retyped between tools", "Telephony that never reaches the CRM", "Payments handled off to the side"],
    technologies: ["REST", "Webhooks", "OAuth", "SIP", "JSON"],
    workSlugs: ["ai-voice-business-automation", "flutter-sip-softphone"],
    faqs: faqs("system integration"),
  },
  {
    slug: "databases",
    path: "/services/databases",
    title: "Databases & Data",
    description: "MySQL, MariaDB, PostgreSQL, Redis, migrations, reporting, and backups.",
    lede: "Data work covers the databases the applications already depend on: design, migration, queries, reporting, and recovery.",
    image: "/enterprise-services.jpg",
    imageAlt: "Data and engineering workspace",
    group: "engineering",
    cards: [
      { title: "MySQL / MariaDB", description: "The relational stores behind many of the web and voice systems." },
      { title: "PostgreSQL", description: "Where the product needs PostgreSQL specifically." },
      { title: "Redis", description: "Cache and short-lived state." },
      { title: "Database Design", description: "Tables shaped around the operation, not a generic template." },
      { title: "Data Migration", description: "Moving data without losing the records that matter." },
      { title: "Reporting", description: "Queries and views people can use." },
      { title: "Query Optimization", description: "The slow path, found and reduced." },
      { title: "Backup & Recovery", description: "A backup that can actually be restored." },
    ],
    problems: ["Reports that lock the application", "Migrations with no rollback", "Backups that were never tested"],
    technologies: ["MySQL", "MariaDB", "PostgreSQL", "Redis", "SQL"],
    workSlugs: ["fix-fensterreinigung-mobile-app"],
    faqs: faqs("databases"),
  },
  {
    slug: "devops-infrastructure",
    path: "/services/devops-infrastructure",
    title: "DevOps & Infrastructure",
    description: "Linux, Docker, CI/CD, web servers, monitoring, networking, and hardening.",
    lede: "This is the engineering view of Cloud & DevOps: how servers, containers, and releases are actually run.",
    image: "/enterprise-services.jpg",
    imageAlt: "Infrastructure workspace",
    group: "engineering",
    cards: [
      { title: "Linux", description: "Production hosts, not only local machines." },
      { title: "Docker", description: "Containers where they make the release repeatable." },
      { title: "CI/CD", description: "A path from change to deployment." },
      { title: "Web Servers", description: "Nginx and Apache in front of the application." },
      { title: "Cloud Deployment", description: "The environment the application is meant to live in." },
      { title: "Monitoring", description: "Enough visibility to know it failed." },
      { title: "Networking", description: "DNS, TLS, and the paths between services." },
      { title: "Security Hardening", description: "Access, firewall, patching, and certificates." },
    ],
    problems: ["Deploys from a laptop", "No log when the site goes down", "Open admin paths"],
    technologies: ["Linux", "Docker", "Nginx", "Apache", "Bash", "SSL/TLS"],
    workSlugs: ["linux-cloud-infrastructure"],
    faqs: faqs("infrastructure"),
  },
  {
    slug: "cloud-linux",
    path: "/services/platforms/cloud-linux",
    title: "Cloud & Linux Infrastructure",
    description: "The server, database, deployment, monitoring, backup, and security layer under an application.",
    lede: "Platforms we design, integrate, or operate: Linux servers, cloud environments, web servers, databases, and the deployment path around them.",
    image: "/enterprise-services.jpg",
    imageAlt: "Server and cloud workspace",
    group: "platform",
    cards: [
      { title: "Linux servers", description: "Production hosts and administration." },
      { title: "Cloud environments", description: "Infrastructure shaped around the application." },
      { title: "Web/application servers", description: "Nginx, Apache, and the app behind them." },
      { title: "Databases", description: "MySQL, MariaDB, PostgreSQL, Redis." },
      { title: "Deployment infrastructure", description: "How a release reaches the server." },
      { title: "Monitoring", description: "Visibility when something fails." },
      { title: "Backup", description: "Recovery that has a procedure." },
      { title: "Security", description: "Access, TLS, firewall, and patching." },
    ],
    problems: ["An application with nowhere reliable to run", "A server only one person understands"],
    technologies: ["Debian", "Ubuntu", "Docker", "Nginx", "MySQL", "PostgreSQL"],
    workSlugs: ["linux-cloud-infrastructure"],
    faqs: faqs("Linux and cloud platforms"),
  },
  {
    slug: "voip",
    path: "/services/platforms/voip",
    title: "VoIP & Contact Center Platforms",
    description: "PBX, contact centers, SIP, IVR, queues, WebRTC, broadcasting, recording, and AI voice.",
    lede: "The communication platforms Sofnology designs, integrates, or operates — from the PBX to the contact center and the voice assistant on top.",
    image: "/Portfolio/4.jpg",
    imageAlt: "Voice platform still life",
    group: "platform",
    cards: [
      { title: "PBX", description: "Business phone platforms, including Asterisk-based systems." },
      { title: "Contact centers", description: "Inbound and outbound agent environments." },
      { title: "SIP infrastructure", description: "Trunks, DIDs, and routing." },
      { title: "IVR", description: "Menus, queues, and fallback." },
      { title: "Queues", description: "How calls wait and land." },
      { title: "WebRTC", description: "Browser calling." },
      { title: "Voice broadcasting", description: "Outbound notifications and campaigns." },
      { title: "Recording and reporting", description: "CDR, recordings, and operational views." },
      { title: "AI voice integration", description: "Assistants attached to the existing platform." },
    ],
    problems: ["A phone system and a contact center that do not meet", "AI voice added without a working trunk"],
    technologies: ["Asterisk", "FreePBX", "VICIdial", "SIP", "WebRTC"],
    workSlugs: ["custom-pbx-contact-center", "voice-broadcasting-platform", "ai-voice-business-automation"],
    faqs: faqs("voice platforms"),
  },
  {
    slug: "web-saas",
    path: "/services/platforms/web-saas",
    title: "Web & SaaS Platforms",
    description: "SaaS applications, portals, dashboards, and multi-user web systems.",
    lede: "Web platforms we can design and build: SaaS products, customer and member portals, dashboards, and internal applications.",
    image: "/digital-growth.jpg",
    imageAlt: "Web product workspace",
    group: "platform",
    cards: [
      { title: "SaaS applications", description: "Multi-user products with accounts and ongoing use." },
      { title: "Customer portals", description: "A private web place for customers." },
      { title: "Member portals", description: "Membership and association platforms." },
      { title: "Dashboards", description: "Operational and management views." },
      { title: "Subscription platforms", description: "Products billed and delivered over time." },
      { title: "Internal web applications", description: "Tools for the team, not the public site." },
      { title: "Multi-user systems", description: "Roles, access, and shared data." },
    ],
    problems: ["A public site with no place for members or staff", "Operations run from spreadsheets"],
    technologies: ["TypeScript", "React", "PHP", "MySQL", "PostgreSQL"],
    workSlugs: ["napc-membership-website"],
    faqs: faqs("web platforms"),
  },
  {
    slug: "business",
    path: "/services/platforms/business",
    title: "Business & Enterprise Systems",
    description: "Internal software, workflows, CRM and ERP connections, reporting, and automation.",
    lede: "Operational systems: internal software, workflows, CRM and ERP connections, reporting, and the automation between them.",
    image: "/enterprise-services.jpg",
    imageAlt: "Business systems workspace",
    group: "platform",
    cards: [
      { title: "Internal software", description: "Tools shaped to how the company works." },
      { title: "Workflow systems", description: "Handoffs that are no longer informal." },
      { title: "CRM integrations", description: "Customer records connected to delivery." },
      { title: "ERP integrations", description: "Finance and operations connected where needed." },
      { title: "Reporting systems", description: "Numbers from the systems of record." },
      { title: "Operational dashboards", description: "A view of the work in progress." },
      { title: "Automation platforms", description: "Repeatable steps between tools." },
    ],
    problems: ["Work passed by email", "CRM and operations that never meet"],
    technologies: ["REST APIs", "MySQL", "PostgreSQL", "Webhooks"],
    workSlugs: ["napc-membership-website", "ai-voice-business-automation"],
    faqs: faqs("business systems"),
  },
  {
    slug: "marketing",
    path: "/services/platforms/marketing",
    title: "Marketing & Analytics Platforms",
    description: "Google Ads, Analytics, Tag Manager, Search Console, tracking, CMS, and landing pages.",
    lede: "The marketing systems we configure and connect: ads, analytics, tags, search, the CMS, and the landing pages they point at.",
    image: "/digital-growth.jpg",
    imageAlt: "Marketing and analytics workspace",
    group: "platform",
    cards: [
      { title: "Google Ads", description: "Account structure and ongoing paid search." },
      { title: "Google Analytics", description: "Traffic and behaviour, read against the business." },
      { title: "Google Tag Manager", description: "Tags and conversion events in one place." },
      { title: "Search Console", description: "How the site is seen in search." },
      { title: "Conversion tracking", description: "Calls, forms, and other actions worth counting." },
      { title: "CMS", description: "The site the campaigns send people to." },
      { title: "Landing-page systems", description: "Pages built for a campaign, not the homepage reused." },
      { title: "Reporting", description: "A view of spend and enquiries together." },
    ],
    problems: ["Campaigns with no conversion record", "A website the ads do not match"],
    technologies: ["Google Ads", "Google Analytics", "Google Tag Manager", "Search Console"],
    workSlugs: ["yanming-digital-growth"],
    faqs: faqs("marketing platforms"),
  },
];

export function getService(slug: string) {
  return servicePages.find((page) => page.slug === slug);
}

export function servicesByGroup(group: ServiceGroup) {
  return servicePages.filter((page) => page.group === group);
}
